### ISSUE TITLE
Entity Span --> CUI

### ISSUE THREAD

**Issue by griff4692** [cambridgeltl/sapbert#1]
Hi - what's the simplest way to go from entity span to CUI?  It seems the HuggingFace model just gets you the [CLS] hidden state representation and you need to use that to find the nearest neighbor in UMLS.  But it wasn't clear how to get that UMLS index

**Comment by hardyqr** [comment]
Hey! I didn't release the UMLS index due to licensing restrictions. But you could check out [this](https://github.com/cambridgeltl/sapbert/blob/main/training_data/generate_pretraining_data.ipynb) notebook to see how they are extracted from UMLS MRCONSO.RFF file (can be downloaded from [this site](https://download.nlm.nih.gov/umls/kss/2021AB/umls-2021AB-mrconso.zip)). 

Once the index is obtained, [this](https://github.com/cambridgeltl/sapbert/blob/main/inference/inference_on_snomed.ipynb) notebook shows how to get the entity span -> CUI mapping through nearest-neighbour's search.

**Comment by griff4692** [comment]
Makes sense - thanks.  Using the `MRCONSO.RFF` makes sense - thanks again and nice work!!
